[package]
name = "dragino_lgt92_tools"
version = "0.2.0"
edition = "2021"
description = "Rust tools to work with Dragino's LGT-92 GPS."
license = "Unlicense"
authors = ["Bruno Dias <dias.h.bruno@gmail.com>"]
email = "dias.h.bruno@gmail.com"

[dependencies]
bytes = "1.1.0"
